# docker-compose.yml
version: '3.8'

services:
  discord:
    build: ./                     # Assuming you have a Dockerfile in the current directory
    # image: kevinthedang/discord-ollama:0.8.4 # If building locally, 'image' is more of a fallback/name tag
    container_name: discord_bot_multi_net
    restart: always
    environment:
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      MODEL: ${MODEL}
      OLLAMA_IP: ${OLLAMA_IP}
      OLLAMA_PORT: ${OLLAMA_PORT}
      REDIS_IP: ${REDIS_IP}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - ollama_network_on_compose
      - redis_network_on_compose
    volumes:
      - discord_bot_data:/src/app       # Named volume mount
      - /var/run/utmp:/var/run/utmp:ro  # Bind mount for /users command
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility]

networks:
  ollama_network_on_compose:
    external: true
    name: self-hosted-ai-starter-kit_demo

  redis_network_on_compose:
    external: true
    name: n8n-ollama-agents_bridge

volumes:
  discord_bot_data: 